import sqlite3

connection = sqlite3.connect('health_care_DB.db')
cursor = connection.cursor()

# Populating "roles" Table
cursor.execute('''INSERT INTO roles(ID, Name) VALUES(1, 'admin');''')
cursor.execute('''INSERT INTO roles(ID, Name) VALUES(2, 'doctor');''')
cursor.execute('''INSERT INTO roles(ID, Name) VALUES(3, 'nurse');''')
cursor.execute('''INSERT INTO roles(ID, Name) VALUES(4, 'patient');''')
cursor.execute('''INSERT INTO roles(ID, Name) VALUES(5, 'family');''')
cursor.execute('''INSERT INTO roles(ID, Name) VALUES(6, 'AI analysts');''')
cursor.execute('''INSERT INTO roles(ID, Name) VALUES(7, 'application developers');''')
cursor.execute('''INSERT INTO roles(ID, Name) VALUES(8, 'device integrators');''')

# Populating "users" Table
cursor.execute('''INSERT INTO users(ID,first_name,last_name,gender,contact_no,role_ID,dob,address,billing,allergies,medical_ID,family,medical_history,medical_condition,emergency_contact)
                VALUES(1,'Saad','Ullah','male',8573212741,1,'1999-08-09 00:00:00','1711 Comm Ave','same','none','XXXXXXX','none','none','none','none');''')
cursor.execute('''INSERT INTO users(ID,first_name,last_name,gender,contact_no,role_ID,dob,address,billing,allergies,medical_ID,family,medical_history,medical_condition,emergency_contact)
                VALUES(2,'Osama','Prof','male',000000,2,'1999-08-09 00:00:00','XXXXXX','same','none','XXXXXXX','none','none','none','none');''')
cursor.execute('''INSERT INTO users(ID,first_name,last_name,gender,contact_no,role_ID,dob,address,billing,allergies,medical_ID,family,medical_history,medical_condition,emergency_contact)
                VALUES(3,'Zaid','Tahir','male',000000,4,'1999-08-09 00:00:00','XXXXXX','same','none','XXXXXXX','none','none','none','none');''')
cursor.execute('''INSERT INTO users(ID,first_name,last_name,gender,contact_no,role_ID,dob,address,billing,allergies,medical_ID,family,medical_history,medical_condition,emergency_contact)
                VALUES(4,'Noor','Alina','female',000000,4,'1999-08-09 00:00:00','XXXXXX','same','none','XXXXXXX','none','none','none','none');''')
cursor.execute('''INSERT INTO users(ID,first_name,last_name,gender,contact_no,role_ID,dob,address,billing,allergies,medical_ID,family,medical_history,medical_condition,emergency_contact)
                VALUES(5,'Jonah','Sameul','male',000000,3,'1999-08-09 00:00:00','XXXXXX','same','none','XXXXXXX','none','none','none','none');''')
cursor.execute('''INSERT INTO users(ID,first_name,last_name,gender,contact_no,role_ID,dob,address,billing,allergies,medical_ID,family,medical_history,medical_condition,emergency_contact)
                VALUES(6,'Mary','Cris','female',000000,4,'1999-08-09 00:00:00','XXXXXX','same','none','XXXXXXX','none','none','none','none');''')
cursor.execute('''INSERT INTO users(ID,first_name,last_name,gender,contact_no,role_ID,dob,address,billing,allergies,medical_ID,family,medical_history,medical_condition,emergency_contact)
                VALUES(7,'Anni','India','male',000000,4,'1999-08-09 00:00:00','XXXXXX','same','none','XXXXXXX','none','none','none','none');''')
cursor.execute('''INSERT INTO users(ID,first_name,last_name,gender,contact_no,role_ID,dob,address,billing,allergies,medical_ID,family,medical_history,medical_condition,emergency_contact)
                VALUES(8,'Cristina','Orla','female',000000,4,'1999-08-09 00:00:00','XXXXXX','same','none','XXXXXXX','none','none','none','none');''')

# Populating "devices" Table
cursor.execute('''INSERT INTO devices(ID,type,unit,date_of_purchase,MAC_address,user_ID,fw_version,sw_version)
                VALUES(1,'Thermometer','F','2020-09-11 00:00:00','xxxxx',2,'xxx','xxx');''')
cursor.execute('''INSERT INTO devices(ID,type,unit,date_of_purchase,MAC_address,user_ID,fw_version,sw_version)
                VALUES(2,'Weight Scale','lbs','2020-09-11 00:00:00','xxxxx',2,'xxx','xxx');''')
cursor.execute('''INSERT INTO devices(ID,type,unit,date_of_purchase,MAC_address,user_ID,fw_version,sw_version)
                VALUES(3,'Blood Pressure Monitor','mmHg','2020-09-11 00:00:00','xxxxx',2,'xxx','xxx');''')
cursor.execute('''INSERT INTO devices(ID,type,unit,date_of_purchase,MAC_address,user_ID,fw_version,sw_version)
                VALUES(4,'Pulse Oximeter','BPM','2020-09-11 00:00:00','xxxxx',5,'xxx','xxx');''')
cursor.execute('''INSERT INTO devices(ID,type,unit,date_of_purchase,MAC_address,user_ID,fw_version,sw_version)
                VALUES(5,'Oximeter','SpO2','2020-09-11 00:00:00','xxxxx',5,'xxx','xxx');''')
cursor.execute('''INSERT INTO devices(ID,type,unit,date_of_purchase,MAC_address,user_ID,fw_version,sw_version)
                VALUES(6,'Glucometer','mmol/L','2020-09-11 00:00:00','xxxxx',5,'xxx','xxx');''')
cursor.execute('''INSERT INTO devices(ID,type,unit,date_of_purchase,MAC_address,user_ID,fw_version,sw_version)
                VALUES(7,'Stadiometer','in','2020-09-11 00:00:00','xxxxx',5,'xxx','xxx');''')

# Populating "measurements" Table
cursor.execute('''INSERT INTO measurements(user_ID,device_ID,value) VALUES(3,1,99);''')
cursor.execute('''INSERT INTO measurements(user_ID,device_ID,value) VALUES(3,2,170);''')
cursor.execute('''INSERT INTO measurements(user_ID,device_ID,value) VALUES(3,3,120);''')
cursor.execute('''INSERT INTO measurements(user_ID,device_ID,value) VALUES(3,4,70);''')
cursor.execute('''INSERT INTO measurements(user_ID,device_ID,value) VALUES(3,5,70);''')
cursor.execute('''INSERT INTO measurements(user_ID,device_ID,value) VALUES(3,6,2);''')
cursor.execute('''INSERT INTO measurements(user_ID,device_ID,value) VALUES(3,7,70);''')
cursor.execute('''INSERT INTO measurements(user_ID,device_ID,value) VALUES(4,1,98);''')
cursor.execute('''INSERT INTO measurements(user_ID,device_ID,value) VALUES(4,2,170);''')
cursor.execute('''INSERT INTO measurements(user_ID,device_ID,value) VALUES(4,3,120);''')
cursor.execute('''INSERT INTO measurements(user_ID,device_ID,value) VALUES(4,4,70);''')
cursor.execute('''INSERT INTO measurements(user_ID,device_ID,value) VALUES(4,5,70);''')
cursor.execute('''INSERT INTO measurements(user_ID,device_ID,value) VALUES(4,6,2);''')
cursor.execute('''INSERT INTO measurements(user_ID,device_ID,value) VALUES(4,7,70);''')
cursor.execute('''INSERT INTO measurements(user_ID,device_ID,value) VALUES(6,1,97);''')
cursor.execute('''INSERT INTO measurements(user_ID,device_ID,value) VALUES(6,2,140);''')
cursor.execute('''INSERT INTO measurements(user_ID,device_ID,value) VALUES(6,3,110);''')
cursor.execute('''INSERT INTO measurements(user_ID,device_ID,value) VALUES(6,4,70);''')
cursor.execute('''INSERT INTO measurements(user_ID,device_ID,value) VALUES(6,5,70);''')
cursor.execute('''INSERT INTO measurements(user_ID,device_ID,value) VALUES(6,6,3);''')
cursor.execute('''INSERT INTO measurements(user_ID,device_ID,value) VALUES(6,7,60);''')
cursor.execute('''INSERT INTO measurements(user_ID,device_ID,value) VALUES(7,1,99);''')
cursor.execute('''INSERT INTO measurements(user_ID,device_ID,value) VALUES(7,2,150);''')
cursor.execute('''INSERT INTO measurements(user_ID,device_ID,value) VALUES(7,3,110);''')
cursor.execute('''INSERT INTO measurements(user_ID,device_ID,value) VALUES(7,4,80);''')
cursor.execute('''INSERT INTO measurements(user_ID,device_ID,value) VALUES(7,5,75);''')
cursor.execute('''INSERT INTO measurements(user_ID,device_ID,value) VALUES(7,6,4);''')
cursor.execute('''INSERT INTO measurements(user_ID,device_ID,value) VALUES(7,7,80);''')
cursor.execute('''INSERT INTO measurements(user_ID,device_ID,value) VALUES(8,1,99);''')
cursor.execute('''INSERT INTO measurements(user_ID,device_ID,value) VALUES(8,2,140);''')
cursor.execute('''INSERT INTO measurements(user_ID,device_ID,value) VALUES(8,3,110);''')
cursor.execute('''INSERT INTO measurements(user_ID,device_ID,value) VALUES(8,4,80);''')
cursor.execute('''INSERT INTO measurements(user_ID,device_ID,value) VALUES(8,5,76);''')
cursor.execute('''INSERT INTO measurements(user_ID,device_ID,value) VALUES(8,6,2);''')
cursor.execute('''INSERT INTO measurements(user_ID,device_ID,value) VALUES(8,7,66);''')

connection.commit()
connection.close()